# Generated by Django 4.0.3 on 2022-04-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("show_weather", "0003_favourite"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="favourite",
            constraint=models.UniqueConstraint(
                fields=("latitude", "longitude"), name="unique coordinates"
            ),
        ),
    ]
