# Generated by Django 4.0.3 on 2022-12-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("show_weather", "0004_favourite_unique coordinates"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favourite",
            name="unique coordinates",
        ),
        migrations.AlterField(
            model_name="weather",
            name="location",
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name="favourite",
            constraint=models.UniqueConstraint(
                fields=("latitude", "longitude", "user"), name="unique coordinates"
            ),
        ),
    ]
