# Generated by Django 4.0.3 on 2022-12-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("show_weather", "0005_remove_favourite_unique coordinates_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Favourite",
        ),
    ]
